Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,9 +29,13 @@ jobs:
           
       - name: Download Shell APK
         run: |
-          
-          curl -L "${{ https://github.com/AetherSX2-backup/AetherSX2-builds/raw/8a6d4b29e2481b53139b6b915142497ec33ebaba/alpha-2928-3060/13215-v1.4-2953.apk }}" -o app/shell.apk
-          
+          # Coba link utama dulu
+          if ! curl -fL "https://github.com/AetherSX2-backup/AetherSX2-builds/raw/master/alpha-2928-3060/13322-v1.4-3060.apk" -o app/shell.apk; then
+            echo "Primary link failed, trying mirror..."
+            # Fallback ke APKMirror (sering lebih awet)
+            curl -fL "https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=578923&pid=1&key=..." -o app/shell.apk || exit 1
+          fi
+
       - name: Build with Gradle
         run: |
           chmod +x gradlew
